---
title: En Marche ! Martinique
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: e.marche972@gmail.com
description: 'Pour ceux qui sont convaincus que le pays est bloqué, qui ont le goût
  du travail, du progrès, du risque, qui vivent pour la liberté, l''égalité, et l''Europe.

'
baseurl: 
url: http://en-marche-martinique.fr
twitter_username: enmarche972
github_username: enmarche972
facebook_app_id: enmarche972
logo: images/logo.svg
sass:
  sass_dir: _scss
pagination:
  enabled: true
  per_page: 12
  permalink: "/page/:num/"
  title: Articles - page :num
  limit: 0
  sort_field: date
  sort_reverse: true
markdown: kramdown
github:
- metadata
languages:
- fr
- en
- ht
default_lang: fr
exclude_from_localization:
- javascript
- images
- css
parallel_localization: true
show_langs_selects: true
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
gems:
- jekyll-seo-tag
- jekyll-paginate-v2
